(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/S_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/S1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/S2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/S3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_S_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/A_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/A2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/A2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/A3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_A_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/WD_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/D2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/D2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/D3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_WD_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/LP_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/LP1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/LP2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/LP3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_LP_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/Cd_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/Cd1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/Cd2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/Cd3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_Cd_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/S+A_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SA1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SA2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SA3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_S+A_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/S+WD_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SD1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SD2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SD3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_S+WD_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/S+LP_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SLP1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SLP2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SLP3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_S+LP_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/A+WD_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/AD1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/AD2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/AD3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_A+WD_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/A+LP_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ALP1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ALP2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ALP3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_A+LP_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/LP+WD_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/LPD1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/LPD2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/LPD3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_LP+WD_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/S+A+WD_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SAD1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SAD2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SAD3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_S+A+WD_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/S+A+LP_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SALP1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SALP2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SALP3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_S+A+LP_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/S+WD+LP_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SDLP1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SDLP2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/SDLP3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_S+WD+LP_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/A+WD+LP_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ADLP1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ADLP2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ADLP3F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_A+WD+LP_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/S+A+WD+LP_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ST42F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ST42F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ST43F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_S+A+WD+LP_vs_CT.txt &

(cuffdiff -p 8 -o /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/S+A+WD+LP+Cd_vs_CT /home/six2h/MFSSoybeanPipeline/refgenome_soybean/Glycine_max.Glycine_max_v2.1.51.gff3 \
	  /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C1F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C2F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/C3F_sorted.bam /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ST51F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ST52F_sorted.bam,/scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/sorted_bams/ST53F_sorted.bam) \
    >& /scratch/six2h/MultiFactorialSoybeanFlowerRonsData/usftp21.novogene.com/cuffdiff_result/logs_cuffdiff/cuffdiff_S+A+WD+LP+Cd_vs_CT.txt &

